// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kamqgsvvimdsgoeapiey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbXFnc3Z2aW1kc2dvZWFwaWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDk2MzQsImV4cCI6MjA2ODA4NTYzNH0.VadJwu0SUasf3aKg65kFhGe-hi-0pmq0zJlJ6bJrTqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});